apiVersion: tekton.dev/v1alpha1
kind: Pipeline
metadata:
  name: hello-pipeline
spec:
  params:
    - name: repository
      description: the git repo
    - name: branch
      description: the branch for the git repo
    - name: statuses_url
      description: the status url to update
    - name: github_user
    - name: github_password
  tasks:
    - name: pipeline-hello-task
      taskRef:
        name: hello-task
      params:
        - name: repository
          value: $(params.repository)
        - name: branch
          value: $(params.branch)
        - name: statuses_url
          value: $(params.statuses_url)
        - name: github_user
          value: $(params.github_user)
        - name: github_password
          value: $(params.github_password)
        - name: status_name
          value: "tekton_pr_status"
        - name: status_state
          value: "pending"
        - name: status_description
          value: "Hello Tekton Pipeline Running"

    - name: pipeline-hello-task
      taskRef:
        name: hello-task
      runAfter:
        - pipeline-hello-task-start
      params:
        - name: repository
          value: $(params.repository)
        - name: branch
          value: $(params.branch)
        - name: statuses_url
          value: $(params.statuses_url)
        - name: github_user
          value: $(params.github_user)
        - name: github_password
          value: $(params.github_password)
        - name: status_name
          value: "tekton_pr_status"
        - name: status_state
          value: "success"
        - name: status_description
          value: "Hello Tekton Pipeline Complete"
