apiVersion: tekton.dev/v1alpha1
kind: Task
metadata:
  name: hello-task
spec:
  inputs:
    params:
      - name: repository
      - name: branch
      - name: statuses_url
      - name: status_name
        default: "tekton_pr_status"
      - name: status_state
        default: "pending"
      - name: status_description
        default: "Running Tekton Pipeline"
      - name: target_url
        default: "https://cloud.ibm.com/devops/pipelines/tekton/"
      - name: github_user
      - name: github_password
  steps:
    - name: echo
      image: curlimages/curl
      command: ["/bin/sh","-c"]
      args:
        - |
          date
          curl -s -o /dev/null --max-time 60 -X POST -u $(inputs.params.github_user):$(inputs.params.github_password) -H "Content-Type: application/json" -d '{"state": "$(inputs.params.status_state)","target_url": "$(inputs.params.target_url)", "description": "$(inputs.params.status_description)","context": "$(inputs.params.status_name)"}' $(inputs.params.statuses_url)
          sleep 30